IF OBJECT_ID('dbo.XXA_OCR_REPORTING_MODIFS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.XXA_OCR_REPORTING_MODIFS
    (
        IdReporting INT IDENTITY(1,1) NOT NULL,
        DateModification DATETIME2(0) NOT NULL CONSTRAINT DF_XXA_OCR_REPORTING_MODIFS_DateModification DEFAULT SYSDATETIME(),
        Utilisateur NVARCHAR(128) NOT NULL,
        RechNr VARCHAR(100) NOT NULL,
        TourNr VARCHAR(20) NOT NULL,
        IsBloque BIT NOT NULL CONSTRAINT DF_XXA_OCR_REPORTING_MODIFS_IsBloque DEFAULT (0),
        IsValidated BIT NOT NULL CONSTRAINT DF_XXA_OCR_REPORTING_MODIFS_IsValidated DEFAULT (0),
        IsLastModifierForTour BIT NOT NULL CONSTRAINT DF_XXA_OCR_REPORTING_MODIFS_IsLastModifierForTour DEFAULT (0),
        DateCreation DATETIME2(0) NOT NULL CONSTRAINT DF_XXA_OCR_REPORTING_MODIFS_DateCreation DEFAULT SYSDATETIME(),
        CONSTRAINT PK_XXA_OCR_REPORTING_MODIFS PRIMARY KEY CLUSTERED (IdReporting ASC),
        CONSTRAINT UX_XXA_OCR_REPORTING_MODIFS_UserRechTour UNIQUE (Utilisateur, RechNr, TourNr)
    );

    CREATE INDEX IX_XXA_OCR_REPORTING_MODIFS_TourNr_Last
        ON dbo.XXA_OCR_REPORTING_MODIFS (TourNr, IsLastModifierForTour, DateModification DESC);

    CREATE INDEX IX_XXA_OCR_REPORTING_MODIFS_RechNr
        ON dbo.XXA_OCR_REPORTING_MODIFS (RechNr);
END;

IF COL_LENGTH('dbo.XXA_OCR_REPORTING_MODIFS', 'IsValidated') IS NULL
BEGIN
    ALTER TABLE dbo.XXA_OCR_REPORTING_MODIFS
    ADD IsValidated BIT NOT NULL
        CONSTRAINT DF_XXA_OCR_REPORTING_MODIFS_IsValidated DEFAULT (0);
END;
